name: On push stg

on:
  push:
    branches:
      - stg

jobs:
  push_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Repository State
        run: |
          git status
          git branch
          git remote -v

      - name: Push to Test Branch
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/stg'
        run: |
          git config user.name "TuNombreDeUsuario"
          git config user.email "TuCorreo@users.noreply.github.com"
          git fetch origin test:refs/remotes/origin/test
          git checkout -B test origin/test || git checkout -b test
          git push origin test
